---
- name: "Manage sssd.conf configuration"
  template:
    src: "{{ sssd_conf_template }}"
    dest: "{{ sssd_conf_path }}"
    owner: root
    group: root
    mode: 0600
  when: sssd_config is defined
  notify: "Restart sssd"
