---
- name: "Restart sssd"
  debug: msg="checking config first"
  changed_when: True
  notify:
    - "Check sssd configuration"
    - "Restart sssd - after config check"

- name: "Check sssd configuration"
  command: "sssctl config-check"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no

- name: "Restart sssd - after config check"
  service:
    name: "{{ sssd_service }}"
    state: "restarted"
